global:
    depth_cut: 24.5
    res: 0.01
    pad: 0.1
    res_bo: 0.003
    flat_project: CAR
    mask_type: sirius
    band: i

ReduceCat:
    min_snr: 10.
    depth_method: fluxerr

MapSyst:
    hist_nbins: 40

COSMOSWeight:
    n_neighbors: 20