global:
    depth_cut: 24.5
    res: 0.01
    pad: 0.1
    res_bo: 0.003
    flat_project: CAR
    mask_type: sirius
    band: i

ReduceCat:
    min_snr: 10.
    depth_method: fluxerr

SystMapper:
    hist_nbins: 40

COSMOSWeight:
    n_neighbors: 20

CatMapper:
    pz_code: ephor_ab
    pz_mark: best
    pz_bins: [0.15,0.50,0.75,1.00,1.50]
    nz_bin_num: 100
    nz_bin_max: 4.0

PowerSpecter:
    ell_bpws: [200.0,600.0,1000.0,1600.0,2200.0,2800.0,3400.0,4200.0,5000.0,6000.0,7000.0,8500.0,10000.0,12000.0,14000.0]
    gaus_covar_type: analytic
    noise_bias_type: analytic
    guess_spectrum: NONE
    add_ssc: True
    mask_thr: 0.5
    mask_systematics: True
    syst_masking_file: hsc_lss_params/systematic_cuts/WIDE_GAMA09H_syst_cuts.txt
    oc_all_bands: True
    ssc_response_prefix: hsc_lss_params/Responses/Response
