global:
    depth_cut: 24.5
    res: 0.01
    pad: 0.1
    res_bo: 0.003
    flat_project: CAR
    mask_type: sirius
    band: i

ReduceCat:
    min_snr: 10.
    depth_method: fluxerr

SystMapper:
    hist_nbins: 40

COSMOSWeight:
    n_neighbors: 20

CatMapper:
    pz_code: ephor_ab
    pz_mark: best
    pz_bins: [0.15,0.50,0.75,1.00,1.50]
    nz_bin_num: 100
    nz_bin_max: 4.0
