global:
    depth_cut: 24.5
    res: 0.01
    pad: 0.1
    res_bo: 0.003
    flat_project: CAR
    mask_type: sirius
    band: i

ReduceCat:
    min_snr: 10.
    depth_method: fluxerr

SystMapper:
    hist_nbins: 40

COSMOSWeight:
    n_neighbors: 20

CatMapper:
    pz_code: ephor_ab
    pz_mark: best
    pz_bins: [0.15,0.50,0.75,1.00,1.50]
    nz_bin_num: 100
    nz_bin_max: 4.0

PowerSpecter:
    ell_bpws: [100.0,200.0,300.0,400.0,600.0,800.0,1000.0,1400.0,1800.0,2200.0,3000.0,3800.0,4600.0,6200.0,7800.0,9400.0,12600.0,15800.0]
    gaus_covar_type: gaus_sim
    noise_bias_type: analytic
    guess_spectrum: NONE
    add_ssc: True
    mask_thr: 0.5
    mask_systematics: False
    oc_dpj_list: [airmass,seeing,sigma_sky]
    oc_all_bands: True
    ssc_response_prefix: hsc_lss_params/Responses/Response
