modules: hsc_lss

launcher: local

stages: 
    - name: ReduceCat
      nprocess: 1
      partition: debug
      walltime: 10
    - name: SystMapper
      nprocess: 1
      partition: regular
      walltime: 60
    - name: PDFMatch
      nprocess: 1
      partition: regular
      walltime: 60
    - name: COSMOSWeight
      nprocess: 1
      partition: debug
      walltime: 30
    - name: CatMapper
      nprocess: 1
      partition: debug
      walltime: 10
    - name: PowerSpecter
      nprocess: 1
      partition: regular
      walltime: 60


inputs:
    #ASCII file containing the paths to all the FITS files containing the raw catalog.
    raw_data: ./hsc_lss_params/input_list_aegis.txt
    #Path to frames FITS file containing the metadata.
    frames_data: /global/cscratch1/sd/damonge/HSC_ceci/PDR1_WIDE_frames.fits
    #Path to directory containing the photo-z pdfs.
    pdf_dir: /global/cscratch1/sd/damonge/HSC_ceci/WIDE_AEGIS
    #Path to file containing the COSMOS-30band data.
    cosmos_data: /global/cscratch1/sd/damonge/HSC_ceci/COSMOS2015_Laigle+_v1.1.fits
    #Path to file containing the raw HSC COSMOS catalog.
    cosmos_hsc: /global/cscratch1/sd/damonge/HSC_ceci/PDR1_DEEP_COSMOS_forced.fits
    #Path to file containing the suggested systematics cuts.
    syst_masking_file: ./hsc_lss_params/systematic_cuts/WIDE_GAMA09H_syst_cuts.txt

config: ./hsc_lss_params/config.yml

resume: True

output_dir: /global/cscratch1/sd/damonge/HSC_ceci/WIDE_AEGIS_out

log_dir: /global/cscratch1/sd/damonge/HSC_ceci/WIDE_AEGIS_out/logs

pipeline_log: /global/cscratch1/sd/damonge/HSC_ceci/WIDE_AEGIS_out/logs/full_log.txt
