modules: hsc_lss

launcher: local

stages: 
    - name: ReduceCat
      nprocess: 1
    - name: SystMapper
      nprocess: 1
    - name: PDFMatch
      nprocess: 1
    - name: COSMOSWeight
      nprocess: 1
    - name: CatMapper
      nprocess: 1
    - name: PowerSpecter
      nprocess: 1


inputs:
    raw_data: ./hsc_lss_params/input_list_aegis.txt
    frames_data: /global/cscratch1/sd/damonge/HSC_ceci/PDR1_WIDE_frames.fits
    pdf_dir: /global/cscratch1/sd/damonge/HSC_ceci/WIDE_AEGIS
    cosmos_data: /global/cscratch1/sd/damonge/HSC_ceci/COSMOS2015_Laigle+_v1.1.fits
    cosmos_hsc: /global/cscratch1/sd/damonge/HSC_ceci/PDR1_DEEP_COSMOS_forced.fits

config: ./hsc_lss_params/config_aegis.yml

resume: True

output_dir: /global/cscratch1/sd/damonge/HSC_ceci/WIDE_AEGIS_out

log_dir: /global/cscratch1/sd/damonge/HSC_ceci/WIDE_AEGIS_out/logs

pipeline_log: /global/cscratch1/sd/damonge/HSC_ceci/WIDE_AEGIS_out/logs/full_log.txt
